server:
  port: 8765
spring:
  application:
    name: spring-cloud-admin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
      discovery:
        ignored-services:
          - zuul
          - ${spring.application.name}


eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
